<?php

namespace Tests\Feature;

use Illuminate\Database\QueryException;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Support\Facades\DB;
use Tests\TestCase;

class TransactionTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        DB::delete('delete from categories');
    }

    public function testTransactionSuccess()
    {
        DB::transaction(function () {
            DB::insert('insert into categories(id, name, description, created_at) values (?, ?, ?, ?)', [
                'GADGET', 'Gadget', 'Gadget Category', "2025-05-05 10:10:10"
            ]);
            DB::insert('insert into categories(id, name, description, created_at) values (?, ?, ?, ?)', [
                'FOOD', 'Food', 'Gadget Category', "2025-05-05 10:10:10"
            ]);
        });

        $result = DB::select('select * from categories');
        self::assertCount(2, $result);
    }

    public function testTransactionFailed()
    {
        try {
            DB::transaction(function () {
                DB::insert('insert into categories(id, name, description, created_at) values (?, ?, ?, ?)', [
                    'GADGET', 'Gadget', 'Gadget Category', "2025-05-05 10:10:10"
                ]);
                DB::insert('insert into categories(id, name, description, created_at) values (?, ?, ?, ?)', [
                    'GADGET', 'Food', 'Gadget Category', "2025-05-05 10:10:10"
                ]);
            });
        } catch (QueryException $error) {
            //expected
        }

        $result = DB::select('select * from categories');
        self::assertCount(0, $result);
    }

    public function testManualTransactionSuccess()
    {
        try {
            DB::beginTransaction();
            DB::insert('insert into categories(id, name, description, created_at) values (?, ?, ?, ?)', [
                'GADGET', 'Gadget', 'Gadget Category', "2025-05-05 10:10:10"
            ]);
            DB::insert('insert into categories(id, name, description, created_at) values (?, ?, ?, ?)', [
                'FOOD', 'Food', 'Gadget Category', "2025-05-05 10:10:10"
            ]);
            DB::commit();
        } catch (QueryException $error) {
            DB::rollBack();
        }

        $result = DB::select('select * from categories');
        self::assertCount(2, $result);
    }

    public function testManualTransactionFailed()
    {
        try {
            DB::beginTransaction();
            DB::insert('insert into categories(id, name, description, created_at) values (?, ?, ?, ?)', [
                'GADGET', 'Gadget', 'Gadget Category', "2025-05-05 10:10:10"
            ]);
            DB::insert('insert into categories(id, name, description, created_at) values (?, ?, ?, ?)', [
                'GADGET', 'Food', 'Gadget Category', "2025-05-05 10:10:10"
            ]);
            DB::commit();
        } catch (QueryException $error) {
            DB::rollBack();
        }

        $result = DB::select('select * from categories');
        self::assertCount(0, $result);
    }

}
